# Path to Python executable; override in environment or application properties if needed
layhtu.python.exe=C:/Users/Hello/AppData/Local/Programs/Python/Python312/python.exe
# Path to the python bridge script (relative to project root when running locally)
layhtu.python.bridge=src/main/resources/Python/api_bridge.py

spring.data.mongodb.uri=mongodb://localhost:27017/LayHtuDB
openweather.api.key=9613be12dc59a63ec516c5b2fc9323dc

# Example with username/password (authSource=admin):
# spring.data.mongodb.uri=mongodb://<username>:<password>@localhost:27017/layhtu?authSource=admin

# Example for MongoDB Atlas (SRV):
# spring.data.mongodb.uri=mongodb+srv://<username>:<password>@cluster0.mongodb.net/layhtu?retryWrites=true&w=majority
